cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^cart/(?P<item_id>[-\w]+)/$', views.add_to_cart, name='add_to_cart'),
    url(r'^cart/list$', views.view_cart, name='view_cart'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', views.delete_item, name='delete_item'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^checkout/status/$', views.payment, name='payment')
]

django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('product.urls', namespace='product')),
    url(r'^', include('cart.urls', namespace='cart'))
]

product/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.list_products, name='list_products')
]

cart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from product.models import Product


class OrderItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def create_item_order(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.product.name


class Payment(models.Model):
    #order = models.ForeignKey(OrderItem, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    number_card = models.CharField(max_length=12)
    expiration = models.CharField(max_length=5)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Transaction(models.Model):
    order = models.ForeignKey(OrderItem, on_delete=models.CASCADE)
    payment = models.OneToOneField(Payment, on_delete=models.SET_NULL, null=True)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order

product/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name

cart/forms.py
from django import forms
from .models import Payment


class PostForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ('name', 'number_card', 'expiration')

cart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from product.models import Product
from cart.models import OrderItem
from .forms import PostForm


def add_to_cart(request, **kwargs):
    product = Product.objects.get(id=kwargs.get('item_id', ''))
    status = OrderItem.objects.get_or_create(product=product)

    if status:
        messages.info(request, "Item " + product.name + " added to Cart.")
        return redirect(reverse('product:list_products'))
    else:
        messages.error(request, "Error to add in the Cart.")
        return redirect(reverse('product:list_products'))


def view_cart(request):
    orders = OrderItem.objects.all()
    products = []

    if orders is not None:
        for order in orders:
            product = Product.objects.get(name=order)
            products.append(product)
        return render(request, 'cart/cart.html', {'products': products})


def delete_item(request, **kwargs):
    item = OrderItem.objects.get(id=kwargs.get('item_id', ''))

    if item:
        item.delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('cart:view_cart'))


def checkout(request):
    form = PostForm(request.POST)

    if form.is_valid():
        OrderItem.objects.all().delete()
        form.save()
        # messages.success(request, "Save Success.")
        return render(request, 'payment/info.html', {})

    return render(request, 'checkout/checkout.html', {})


def payment(request):
    return render(request, 'payment/info.html', {})

product/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.utils import timezone
from .models import Product


def list_products(request):
    #products = Product.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    products = Product.objects.all()
    return render(request, 'list/list.html', {'products': products})

cart/templates/cart/cart.html
{% extends 'base.html' %}

{% block content %}

<div class="row mt-5">
    <h2>Shopping Cart</h2>
    <div class="col-sm-12">
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>
                        <input type="number" class="form-control quantity" id="quantity_{{product.id}}" min="1"
                               max="{{product.quantity}}" value="1" required>
                    </td>
                    <td>$ {% load humanize %}
                        {{ product.price|floatformat:2|intcomma }}
                    </td>
                    <td>
                        <a href="{% url 'cart:delete_item' product.id %}" class="btn btn-danger">
                            <i class="fas fa-minus"></i>
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4" class="text-center"> You have not added any items yet.</td>
                </tr>
                {% endfor %}
                {% if products %}
                <tr>
                    <td></td>
                    <td></td>
                    <td>Total: $ <span>0000</span></td>
                    <td><a href="{% url 'cart:checkout' %}" class="btn btn-primary">CONTINUE</a></td>
                </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

cart/templates/checkout/checkout.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<div class="row mt-5">
    <h2>Checkout</h2>
    <div class="col-sm-12">
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="numberCard">Number Card</label>
                <input type="text" class="form-control" id="number_card" name="number_card" placeholder="0000 0000 0000 0000" maxlength="16" required>
            </div>
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Your Name" required>
            </div>
            <div class="form-group">
                <label for="expiration">Expiration date</label>
                <input type="text" class="form-control" id="expiration" name="expiration" placeholder="00/00" maxlength="5" required>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

cart/templates/payment/info.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<div class="row mt-5">
    <div class="col-sm-12">
        <h2>Status</h2>
        <p>Payment accept.</p>
    </div>
</div>

{% endblock %}

product/templates/list/list.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<div class="row mt-5">
    <h2>Product List</h2>
    <div class="col-sm-12">
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col" style="width: 120px;">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.description }}</td>
                    <td>$ {% load humanize %}
                        {{ product.price|floatformat:2|intcomma }}
                    </td>
                    <td>{{ product.quantity }}</td>
                    <td>
                        <a href="{% url 'cart:add_to_cart' product.id %}" class="btn btn-primary">
                            <i class="fas fa-cart-plus"></i>
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6" class="text-center"> You have not products yet.</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load staticfiles %}
<html>
<head>
    <title>Products</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
          integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="page-header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02"
                aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Products <span class="sr-only">(current)</span></a>
                </li>
            </ul>

            <a href="{% url 'cart:view_cart' %}" class="btn btn-outline-light my-2 my-sm-0">
                <i class="fas fa-shopping-cart"></i>
            </a>

        </div>
    </nav>
</div>

{% include 'messages.html' %}
<div class="content container">
    {% block content %}
    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
<script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
</script>

{% block script %}{% endblock script %}
</body>
</html>

templates/messages.html
{% if messages %}

{% for message in messages %}

{% if message.tags == 'error' %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

{% else %}

<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}
{% endfor %}

{% endif %}